### ISSUE TITLE
registry config is not found in 

### ISSUE THREAD

**Issue by jockchou** [youzan/zanhttpdemo#2]
Fatal error: Uncaught Zan\Framework\Network\ServerManager\Exception\ServerConfigException: registry config is not found in /home/vagrant/gitroot/zanhttpdemo/vendor/zanphp/zan/src/Network/ServerManager/ServerDiscoveryInitiator.php:20

**Comment by xhjcehust** [comment]
需要添加registry.php配置，详细参考http://zanphpdoc.zanphp.io/config/registry.html
